name: Test & Lint

on: [push]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@main    

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14

      - name: Cache node_modules 📦
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}    
          restore-keys: |
            ${{ runner.os }}-modules-      

      - name: Install dependencies 👨🏻‍💻
        run: yarn run bootstrap || npx lerna bootstrap

      - name: Run compile 🏗
        run: npx --no-install lerna run compile

      - name: Run linter 👀
        run: npx --no-install lerna run format

      - name: Run tests 🧪
        run: npx --no-install lerna run test